version: "0.0.3.(base)"
# 脚本请求设置
default-settings:
  ua: "Mozilla/5.0 (Win64; x64)"
  domain: "google.com"
  ip: "0.0.0.0"
  url: "https://www.google.com"
  port: "8080"
  cmd: "whoami"
  threads: 50
  timeout: 5
  cookie: null
  # verify验证
  ssl: false

rebound-settings:
  # 默认监听设置
  rhost: "0.0.0.0"
  lhost: "0.0.0.0"
  rport: "8080"
  lport: "9527"

# rich 默认开关 弃用
# rich-flag: true
# yaml poc 文件地址
yaml-pocs-dir: "yml"


file-settings:
  # poc默认读取文件地址，建议不修改
  file: "etc/passwd"
  # 批量(batch)模式下默认读取文件地址
  batch-work-file: "batch/url.txt"

proxy-settings:
  proxy: null
  # proxy: "http://198.18.0.3:1082" "198.18.0.3:1082"

api-keys:
  # ceye-dns
  ceye-dns: ""
  ceye-api: ""
  # censys-api 免费注册
  censys:
    api: ""
    secret: ""
    auth: "Basic NWUyMDM2YzItZmIyMS00NGMwLWI5N2MtZTBmNjQ0ZGZmODFiOmExRkxabUVlWHYzR1pocVpQNHVsMDdGaXNxM2ZqbFRR"
  # shodan
  shodan-api: ""
  # virustotal-api 免费注册
  virustotal-api: ""
  # dnsdumpster-csrftoken 请求包里
  dnsdump-csrftoken: "uxXaL6TLzz2H7LSTcufBjR60ahvqBHJiitZoXqZWNNCVfk6sxySdNUrjUctMEdZU"
  # fofa
  fofa:
    key: ""
    email: ""
  # hunter
  yt-key: ""
  # viewdns 免费注册，每月250次
  viewdns-key: ""
  # fullhunt-api 每月100 https://fullhunt.io/
  fullhunt-api: ""
  # zoomeye zoomeye国内外账户不通用，key通用
  zoomeye-key: ""
  # quake
  quake-key: ""
  # https://app.binaryedge.io/services/query
  binaryedge-key: ""
  # whoisxmlapi.com 每月500条
  whoisxmlapi-key: ""
  # hunter.how 每天500 注意不是hunter，网站地址hunter.how
  hunter-how-key: ""
  # DayDayMap
  daydaymap-key: ""
# securitytrails.com接口网站的密钥 每个50次，免费注册,可注册多个，当检测无使用次数时自动遍历替换
securitytrails-keys:
  api-list:
    - "n8im4xpZJnyWAlLdmNTCAtQ994ufTR-t"
# cmd5
cmd5:
  key: ""
  mail: ""